networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.55.1
        subnet: 192.168.55.0/24
      driver: default
services:
  node0:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 0
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.10
    ports:
    - 9090:9090
  node1:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 1
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.11
    ports:
    - 9091:9091
  node10:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 10
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.20
    ports:
    - 9100:9100
  node11:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 11
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.21
    ports:
    - 9101:9101
  node12:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 12
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.22
    ports:
    - 9102:9102
  node13:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 13
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.23
    ports:
    - 9103:9103
  node14:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 14
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.24
    ports:
    - 9104:9104
  node15:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 15
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.25
    ports:
    - 9105:9105
  node16:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 16
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.26
    ports:
    - 9106:9106
  node17:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 17
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.27
    ports:
    - 9107:9107
  node18:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 18
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.28
    ports:
    - 9108:9108
  node19:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 19
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.29
    ports:
    - 9109:9109
  node2:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 2
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.12
    ports:
    - 9092:9092
  node20:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 20
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.30
    ports:
    - 9110:9110
  node21:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 21
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.31
    ports:
    - 9111:9111
  node22:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 22
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.32
    ports:
    - 9112:9112
  node23:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 23
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.33
    ports:
    - 9113:9113
  node24:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 24
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.34
    ports:
    - 9114:9114
  node25:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 25
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.35
    ports:
    - 9115:9115
  node26:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 26
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.36
    ports:
    - 9116:9116
  node27:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 27
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.37
    ports:
    - 9117:9117
  node28:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 28
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.38
    ports:
    - 9118:9118
  node29:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 29
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.39
    ports:
    - 9119:9119
  node3:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 3
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.13
    ports:
    - 9093:9093
  node30:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 30
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.40
    ports:
    - 9120:9120
  node31:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 31
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.41
    ports:
    - 9121:9121
  node32:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 32
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.42
    ports:
    - 9122:9122
  node33:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 33
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.43
    ports:
    - 9123:9123
  node34:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 34
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.44
    ports:
    - 9124:9124
  node35:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 35
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.45
    ports:
    - 9125:9125
  node36:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 36
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.46
    ports:
    - 9126:9126
  node37:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 37
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.47
    ports:
    - 9127:9127
  node38:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 38
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.48
    ports:
    - 9128:9128
  node39:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 39
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.49
    ports:
    - 9129:9129
  node4:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 4
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.14
    ports:
    - 9094:9094
  node5:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 5
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.15
    ports:
    - 9095:9095
  node6:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 6
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.16
    ports:
    - 9096:9096
  node7:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 7
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.17
    ports:
    - 9097:9097
  node8:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 8
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.18
    ports:
    - 9098:9098
  node9:
    build: .
    environment:
      ALGORITHM: blockchain
      EMPTY: null
      PID: 9
      TOPOLOGY: topologies/blockchain.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.55.19
    ports:
    - 9099:9099
version: '3.7'
x-common-variables:
  EMPTY: null
  TOPOLOGY: topologies/blockchain.yaml
